Repository indigo-web/indigo, pull requests merged in 2024-01, with the labels that each got.

#121 Renamed response builder methods, fixed https self-signed certs generating, internal restructuring
  http/response.go
  http/response_test.go
  https.go
  indi.go
  indigo_test.go
  internal/httptest/dump_test.go
  internal/initialize/initializers.go
  internal/server/http/http_bench_test.go
  internal/server/tcp/dummy/client.go
  internal/transport/http1/parser_test.go
  router/inbuilt/middlewares_test.go
  version
Labels: enhancement, bugfix

#122 New response predicates in http package and small internal improvements
  http/request.go
  http/response.go
  indigo_test.go
  internal/response/fields.go
  internal/transport/http1/serializer.go
  version
Labels: documentation, enhancement

#123 Better performance of dynamic routing
  router/inbuilt/internal/radix/arrmap.go
  router/inbuilt/internal/radix/arrmap_test.go
  router/inbuilt/internal/radix/tree.go
  router/inbuilt/internal/radix/tree_bench_test.go
  router/inbuilt/registrar.go
  version
Labels: optimisation

#124 Avoid printing status.CloseConnection responses in logging middleware
  http/status/codes.go
  router/inbuilt/middleware/logging.go
  version
Labels: enhancement

#125 Eliminated constant 16-byte allocation, extended test-coverage, minor internal updates
  examples/helloworld_norouter/helloworld.go
  go.mod
  go.sum
  http/body.go
  http/proto/proto.go
  http/proto/proto_string.go
  http/request.go
  indigo_test.go
  internal/initialize/initializers.go
  internal/requestgen/genrequests.go
  internal/server/http/http.go
  internal/server/http/http_bench_test.go
  internal/server/http/http_test.go
  internal/server/tcp/dummy/client.go
  internal/server/tcp/dummy/client_test.go
  internal/stash/reader.go
  internal/stash/reader_test.go
  internal/transport/http1/body.go
  internal/transport/http1/body_test.go
  internal/transport/http1/parser.go
  internal/transport/http1/parser_bench_test.go
  internal/transport/http1/parser_test.go
  router/simple/simple.go
  version
Labels: enhancement

#126 Fix bug, when mutators would be called twice on error
  http/status/errors.go
  internal/initialize/initializers.go
  internal/stash/reader.go
  internal/stash/reader_test.go
  internal/transport/http1/body.go
  internal/transport/http1/parser.go
  internal/transport/http1/parser_test.go
  internal/transport/http1/transport.go
  router/inbuilt/inbuilt.go
  router/inbuilt/inbuilt_test.go
  version
Labels: bugfix, optimisation

#128 Storing version in a constant, improve simple router and adjust http.Respond behaviour
  examples/helloworld_norouter/helloworld.go
  http/response.go
  indigo_test.go
  internal/server/http/http_test.go
  internal/transport/http1/parser.go
  router/inbuilt/middleware/serverheader.go
  router/simple/simple.go
  version
  version.go
Labels: enhancement, feature
